foreground         #B14461
#background        #201D2D  # This looks way better but not good for low contrast, high brightness walls
background         #201E23
cursor             #A3D7C0 

active_tab_foreground     #201D2D
active_tab_background     #B14461
inactive_tab_foreground   #B14461
inactive_tab_background   #201D2D

active_border_color   #5C283F
inactive_border_color #B14461
bell_border_color     #683622

color0       #201D2D
color8       #4F2D30
color1       #A3D7C0
color9       #5C283F
color2       #843028
color10      #843028
color3       #5B2D28
color11      #5B2D28
color4       #413134
color12      #413134
color5       #553134
color13      #553134
color6       #6B2E2E
color14      #6B2E2E
color7       #B14461
color15      #B14461
