general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    col.active_border = rgba(a300e9ff) rgba(ddff00ee) 45deg
    col.inactive_border = rgba(595959aa)
}

decoration {
    rounding = 4
    blur {
        enabled = true
        size = 10
        passes = 2
        new_optimizations = on
    }
    shadow {
        enabled = false
        range = 4
        render_power = 3
    }
}

bindd = SUPER, R, Launch apps, exec, omarchy-launch-walker

windowrule = opacity 0.90 0.90, match:class ^(firefox)$
windowrule = opacity 0.90 0.90, match:class ^(Google-chrome)$
windowrule = opacity 0.80 0.80, match:class ^([Cc]ode)$
windowrule = opacity 0.80 0.80, match:class ^(code-oss)$
windowrule = opacity 1.00 1.00, match:class ^(kitty)$
windowrule = opacity 0.80 0.80, match:class ^(org.kde.dolphin)$
windowrule = opacity 0.80 0.70, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = opacity 0.80 0.70, match:class ^(nm-connection-editor)$
windowrule = opacity 0.70 0.70, match:class ^([Ss]team)$
windowrule = opacity 0.70 0.70, match:class ^([Ss]potify)$
windowrule = opacity 0.80 0.80, match:class ^(vesktop)$
windowrule = opacity 0.80 0.80, match:class ^(discord)$
windowrule = opacity 0.80 0.80, match:class ^(Signal)$

windowrule = float on, match:class ^(vlc)$
windowrule = float on, match:class ^(org.kde.ark)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:title ^(Open)$
windowrule = float on, match:title ^(Save As)$
windowrule = float on, match:title ^(Confirm to replace files)$

windowrule = workspace 1, match:class ^(google-chrome)$
windowrule = workspace 1, match:class ^(obsidian)$
windowrule = workspace 2, match:class ^(kitty)$
windowrule = workspace 3, match:class ^(Slack)$
windowrule = workspace 4, match:class ^(discord)$
windowrule = workspace 5, match:class ^(Spotify)$

layerrule = blur on, match:tag notifications
windowrule = border_size 0, match:fullscreen 1
